// Code generated by "stringer -type StatusCode"; DO NOT EDIT.

package dimse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusSuccess-0]
	_ = x[StatusCancel-65024]
	_ = x[StatusSOPClassNotSupported-274]
	_ = x[StatusInvalidArgumentValue-277]
	_ = x[StatusInvalidAttributeValue-262]
	_ = x[StatusInvalidObjectInstance-279]
	_ = x[StatusUnrecognizedOperation-529]
	_ = x[StatusNotAuthorized-292]
	_ = x[StatusPending-65280]
	_ = x[CStoreOutOfResources-42752]
	_ = x[CStoreCannotUnderstand-49152]
	_ = x[CStoreDataSetDoesNotMatchSOPClass-43264]
	_ = x[CFindUnableToProcess-49152]
	_ = x[CMoveOutOfResourcesUnableToCalculateNumberOfMatches-42753]
	_ = x[CMoveOutOfResourcesUnableToPerformSubOperations-42754]
	_ = x[CMoveMoveDestinationUnknown-43009]
	_ = x[CMoveDataSetDoesNotMatchSOPClass-43264]
	_ = x[StatusAttributeValueOutOfRange-278]
	_ = x[StatusAttributeListError-263]
}

const _StatusCode_name = "StatusSuccessStatusInvalidAttributeValueStatusAttributeListErrorStatusSOPClassNotSupportedStatusInvalidArgumentValueStatusAttributeValueOutOfRangeStatusInvalidObjectInstanceStatusNotAuthorizedStatusUnrecognizedOperationCStoreOutOfResourcesCMoveOutOfResourcesUnableToCalculateNumberOfMatchesCMoveOutOfResourcesUnableToPerformSubOperationsCMoveMoveDestinationUnknownCStoreDataSetDoesNotMatchSOPClassCStoreCannotUnderstandStatusCancelStatusPending"

var _StatusCode_map = map[StatusCode]string{
	0:     _StatusCode_name[0:13],
	262:   _StatusCode_name[13:40],
	263:   _StatusCode_name[40:64],
	274:   _StatusCode_name[64:90],
	277:   _StatusCode_name[90:116],
	278:   _StatusCode_name[116:146],
	279:   _StatusCode_name[146:173],
	292:   _StatusCode_name[173:192],
	529:   _StatusCode_name[192:219],
	42752: _StatusCode_name[219:239],
	42753: _StatusCode_name[239:290],
	42754: _StatusCode_name[290:337],
	43009: _StatusCode_name[337:364],
	43264: _StatusCode_name[364:397],
	49152: _StatusCode_name[397:419],
	65024: _StatusCode_name[419:431],
	65280: _StatusCode_name[431:444],
}

func (i StatusCode) String() string {
	if str, ok := _StatusCode_map[i]; ok {
		return str
	}
	return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
